id: https://w3id.org/ontogpt/recipe
name: recipe-template
title: Food Recipe Template
description: >-
  A template for food recipes
license: https://creativecommons.org/publicdomain/zero/1.0/
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  linkml: https://w3id.org/linkml/
  recipe: http://w3id.org/ontogpt/recipe/
  FOODON: http://purl.obolibrary.org/obo/FOODON_
  UO: http://purl.obolibrary.org/obo/UO_
  dcterms: http://purl.org/dc/terms/
  HANCESTRO: http://purl.obolibrary.org/obo/HANCESTRO_
  BFO: http://purl.obolibrary.org/obo/BFO_
  AUTO: http://example.org/auto/
  RO: http://purl.obolibrary.org/obo/RO_
  qudt: http://qudt.org/schema/qudt/
  dbpediaont: http://dbpedia.org/ontology/

# This template incorportates syntax from
# linkml-owl to define OWL interpretations
# and enable advanced functionality.
# https://linkml.io/linkml-owl/templates/

default_prefix: recipe
default_range: string

imports:
  - linkml:types
  - core

classes:
  Recipe:
    tree_root: true
    close_mappings:
      - FOODON:00004081  # food recipe
    attributes:
      url:
        identifier: true
        range: uriorcurie
        slot_uri: rdf:Resource
        annotations:
          prompt.skip: true
      label:
        description: the name of the recipe
        slot_uri: rdfs:label
        annotations:
          owl: AnnotationProperty, AnnotationAssertion
      description:
        description: a brief textual description of the recipe
        slot_uri: dcterms:description
        annotations:
          owl: AnnotationProperty, AnnotationAssertion
      categories:
        description: a semicolon separated list of the categories to which this recipe belongs
        range: RecipeCategory
        multivalued: true
        slot_uri: dcterms:subject
        annotations:
          owl: AnnotationAssertion
      ingredients:
        description: a semicolon separated list of the ingredients plus quantities of the recipe
        multivalued: true
        range: Ingredient
        slot_uri: FOODON:00002420
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom
      steps:
        description: a semicolon separated list of the individual steps involved in this recipe
        multivalued: true
        range: Step
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom
    annotations:
      owl: Class
      owl.template: |
        EquivalentClasses(
          {{url}}
          ObjectIntersectionOf(
            recipe:Recipe
            
            {% for step in steps %}
            ObjectSomeValuesFrom(
              recipe:steps
              {{tr(step)}}
            )
            {% endfor %}
            {% for ingredient in ingredients %}
            ObjectSomeValuesFrom(
              FOODON:00002420
              {{tr(ingredient)}}
            )
            {% endfor %}
          )
        )
  Ingredient:
    is_a: CompoundExpression
    class_uri: FOODON:00004085
    annotations:
      owl: IntersectionOf
    attributes:
      food_item:
        description: the food item
        range: FoodItem
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom
      amount:
        description: the quantity of the ingredient, e.g. 2 lbs
        range: Quantity
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom

  Quantity:
    is_a: CompoundExpression
    annotations:
      owl: IntersectionOf
    attributes:
      value:
        description: the value of the quantity
        #range: float
        annotations:
          owl: DataProperty, DataHasValue
      unit:
        description: the unit of the quantity, e.g. grams, cups, etc.
        range: Unit
        slot_uri: qudt:unit
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom

  Step:
    is_a: CompoundExpression
    class_uri: FOODON:00004087
    annotations:
      owl: IntersectionOf
    attributes:
      action:
        description: the action taken in this step (e.g. mix, add)
        range: Action
      inputs:
        description: a semicolon separated list of the inputs of this step
        range: FoodItem
        multivalued: true
        slot_uri: RO:0002233
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom
      outputs:
        description: a semicolon separated list of the outputs of this step
        range: FoodItem
        multivalued: true
        slot_uri: RO:0002234
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom
      utensils:
        description: the kitchen utensil used in this step (e.g. pan, bowl)
        range: UtensilType
        multivalued: true
        slot_uri: RO:0002500
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom

  FoodItem:
    is_a: CompoundExpression
    annotations:
      owl: IntersectionOf
    attributes:
      food:
        description: the food item
        range: FoodType
        slot_uri: BFO:0000051
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom
      state:
        description: the state of the food item (e.g. chopped, diced)
        annotations:
          owl: DataProperty, DataHasValue

  FoodType:
    is_a: NamedEntity
    id_prefixes:
      - dbpediaont
      - FOODON
    annotations:
      annotators: sqlite:obo:foodon, sqlite:obo:dbpediaont

  RecipeCategory:
    is_a: NamedEntity
    id_prefixes:
      - dbpediaont
      - FOODON
      - HANCESTRO
    annotations:
      annotators: sqlite:obo:foodon, sqlite:obo:dbpediaont

  Action:
    is_a: NamedEntity
    id_prefixes:
      - dbpediaont
      - FOODON
    annotations:
      annotators: sqlite:obo:dbpediaont, sqlite:obo:foodon

  UtensilType:
    is_a: NamedEntity
    id_prefixes:
      - dbpediaont
      - FOODON
    annotations:
      annotators: sqlite:obo:dbpediaont, sqlite:obo:foodon

  Unit:
    is_a: NamedEntity
    id_prefixes:
      - UO
      - NCIT
      - dbpediaont
    annotations:
      annotators: sqlite:obo:uo, sqlite:obo:dbpediaont, sqlite:obo:foodon
